### ISSUE TITLE
Action to set review_assignments to "Not Available" when reviewer is assigned (self assigment)

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-server#199] opened 2021-01-28 22:39 UTC
Trigger: OnAssignment

- needs to check all sections are assigned, and only set "not_available" if all sections are.

**Comment by CarlosNZ** [comment] 2021-01-31 23:48
I think this is a duplicate of #195. Didn't we have something else that needed to happen on Review submit that we were going to include in this issue?

**Comment by nmadruga** [comment] 2021-02-04 23:12
The self-assignment should change other review_assigment statuses to NOT AVAILABLE. And for review level 1, although there might be more than one review_assigment (for the same sections/application) we don't change the status, so after the section is assigned to the reviewer there should be one ASSIGNED and others are still AVAILABLE. 

That is to simplify the re-assignment for now.

**Closed** 2021-02-18 22:57 UTC
Labels: Effort: 3, Epic #22: Consolidation of Reviews, Feature: new, Sprint20
